//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mimsys.MS.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MSVisitResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MSVisitResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mimsys.MS.Resources.Forms.MSVisitResx", typeof(MSVisitResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accident Place.
        /// </summary>
        public static string AccidentPlace {
            get {
                return ResourceManager.GetString("AccidentPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accident Reg. Code.
        /// </summary>
        public static string AccidentRegCode {
            get {
                return ResourceManager.GetString("AccidentRegCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance Alert.
        /// </summary>
        public static string AdvanceAlert {
            get {
                return ResourceManager.GetString("AdvanceAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance Utilize.
        /// </summary>
        public static string AdvanceUtilize {
            get {
                return ResourceManager.GetString("AdvanceUtilize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Days.
        /// </summary>
        public static string AgeDays {
            get {
                return ResourceManager.GetString("AgeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Months.
        /// </summary>
        public static string AgeMonths {
            get {
                return ResourceManager.GetString("AgeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Years.
        /// </summary>
        public static string AgeYears {
            get {
                return ResourceManager.GetString("AgeYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Flag.
        /// </summary>
        public static string AlertFlag {
            get {
                return ResourceManager.GetString("AlertFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergy Flag.
        /// </summary>
        public static string AllergyFlag {
            get {
                return ResourceManager.GetString("AllergyFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Date.
        /// </summary>
        public static string ApplicationDate {
            get {
                return ResourceManager.GetString("ApplicationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Co-Pay Limit.
        /// </summary>
        public static string ApplyCoPayLimit {
            get {
                return ResourceManager.GetString("ApplyCoPayLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Visit Limit.
        /// </summary>
        public static string ApplyVisitLimit {
            get {
                return ResourceManager.GetString("ApplyVisitLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment No..
        /// </summary>
        public static string AppointmentNumber {
            get {
                return ResourceManager.GetString("AppointmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization By.
        /// </summary>
        public static string AuthorizationBy {
            get {
                return ResourceManager.GetString("AuthorizationBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Date.
        /// </summary>
        public static string AuthorizationDate {
            get {
                return ResourceManager.GetString("AuthorizationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization End.
        /// </summary>
        public static string AuthorizationEnd {
            get {
                return ResourceManager.GetString("AuthorizationEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Number.
        /// </summary>
        public static string AuthorizationNumber {
            get {
                return ResourceManager.GetString("AuthorizationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Start.
        /// </summary>
        public static string AuthorizationStart {
            get {
                return ResourceManager.GetString("AuthorizationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize.
        /// </summary>
        public static string Authorize {
            get {
                return ResourceManager.GetString("Authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized.
        /// </summary>
        public static string Authorized {
            get {
                return ResourceManager.GetString("Authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automate Lab Collection.
        /// </summary>
        public static string AutomateLabCollection {
            get {
                return ResourceManager.GetString("AutomateLabCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avail First.
        /// </summary>
        public static string AvailFirst {
            get {
                return ResourceManager.GetString("AvailFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billed.
        /// </summary>
        public static string Billed {
            get {
                return ResourceManager.GetString("Billed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Code.
        /// </summary>
        public static string BillingCode {
            get {
                return ResourceManager.GetString("BillingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Number.
        /// </summary>
        public static string BillNumber {
            get {
                return ResourceManager.GetString("BillNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Visit.
        /// </summary>
        public static string CancelVisit {
            get {
                return ResourceManager.GetString("CancelVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Select.
        /// </summary>
        public static string CaseSelect {
            get {
                return ResourceManager.GetString("CaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Transfer.
        /// </summary>
        public static string CaseTransfer {
            get {
                return ResourceManager.GetString("CaseTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Billed.
        /// </summary>
        public static string CheckBilled {
            get {
                return ResourceManager.GetString("CheckBilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckedIn.
        /// </summary>
        public static string CheckedIn {
            get {
                return ResourceManager.GetString("CheckedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Encounter/Bill Created.
        /// </summary>
        public static string CheckEncounterBillCreated {
            get {
                return ResourceManager.GetString("CheckEncounterBillCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check OP Advance.
        /// </summary>
        public static string CheckOPAdvance {
            get {
                return ResourceManager.GetString("CheckOPAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out Time.
        /// </summary>
        public static string CheckOutTime {
            get {
                return ResourceManager.GetString("CheckOutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Policy Expiry Date.
        /// </summary>
        public static string CheckPolicyExpiryDate {
            get {
                return ResourceManager.GetString("CheckPolicyExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Speciality.
        /// </summary>
        public static string CheckSpeciality {
            get {
                return ResourceManager.GetString("CheckSpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Time.
        /// </summary>
        public static string CheckTime {
            get {
                return ResourceManager.GetString("CheckTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic Code.
        /// </summary>
        public static string ClinicCode {
            get {
                return ResourceManager.GetString("ClinicCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic Description.
        /// </summary>
        public static string ClinicDescription {
            get {
                return ResourceManager.GetString("ClinicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation.
        /// </summary>
        public static string Consultation {
            get {
                return ResourceManager.GetString("Consultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation Check.
        /// </summary>
        public static string ConsultationCheck {
            get {
                return ResourceManager.GetString("ConsultationCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation Count.
        /// </summary>
        public static string ConsultationCount {
            get {
                return ResourceManager.GetString("ConsultationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation Description.
        /// </summary>
        public static string ConsultationDescription {
            get {
                return ResourceManager.GetString("ConsultationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation Setup.
        /// </summary>
        public static string ConsultationSetup {
            get {
                return ResourceManager.GetString("ConsultationSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation Type.
        /// </summary>
        public static string ConsultationType {
            get {
                return ResourceManager.GetString("ConsultationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation Type Code.
        /// </summary>
        public static string ConsultationTypeCode {
            get {
                return ResourceManager.GetString("ConsultationTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consult Bills.
        /// </summary>
        public static string ConsultBills {
            get {
                return ResourceManager.GetString("ConsultBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consult Name.
        /// </summary>
        public static string ConsultName {
            get {
                return ResourceManager.GetString("ConsultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Clients.
        /// </summary>
        public static string CorporateClients {
            get {
                return ResourceManager.GetString("CorporateClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criedt Patient.
        /// </summary>
        public static string CriedtPatient {
            get {
                return ResourceManager.GetString("CriedtPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type.
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductible Amount.
        /// </summary>
        public static string DeductibleAmount {
            get {
                return ResourceManager.GetString("DeductibleAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductible Balance.
        /// </summary>
        public static string DeductibleBalance {
            get {
                return ResourceManager.GetString("DeductibleBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default E&amp;&amp;M Code.
        /// </summary>
        public static string DefaultEMCode {
            get {
                return ResourceManager.GetString("DefaultEMCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Order.
        /// </summary>
        public static string DeliveryOrder {
            get {
                return ResourceManager.GetString("DeliveryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dental.
        /// </summary>
        public static string Dental {
            get {
                return ResourceManager.GetString("Dental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Code.
        /// </summary>
        public static string DepartmentCode {
            get {
                return ResourceManager.GetString("DepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department wise.
        /// </summary>
        public static string DepartmentWise {
            get {
                return ResourceManager.GetString("DepartmentWise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dermatology.
        /// </summary>
        public static string Dermatology {
            get {
                return ResourceManager.GetString("Dermatology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Amount.
        /// </summary>
        public static string DiscountAmount {
            get {
                return ResourceManager.GetString("DiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Category Code.
        /// </summary>
        public static string DiscountCategoryCode {
            get {
                return ResourceManager.GetString("DiscountCategoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Category Description.
        /// </summary>
        public static string DiscountCategoryDescription {
            get {
                return ResourceManager.GetString("DiscountCategoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Percentage.
        /// </summary>
        public static string DiscountPercentage {
            get {
                return ResourceManager.GetString("DiscountPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Notify Flag.
        /// </summary>
        public static string DoctorNotifyFlag {
            get {
                return ResourceManager.GetString("DoctorNotifyFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EHR Alert Message.
        /// </summary>
        public static string EHRAlertMessage {
            get {
                return ResourceManager.GetString("EHRAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eligible Amount.
        /// </summary>
        public static string EligibleAmount {
            get {
                return ResourceManager.GetString("EligibleAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eligible Type.
        /// </summary>
        public static string EligibleType {
            get {
                return ResourceManager.GetString("EligibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer.
        /// </summary>
        public static string Employer {
            get {
                return ResourceManager.GetString("Employer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encounter Unique Code.
        /// </summary>
        public static string EncounterUniqueCode {
            get {
                return ResourceManager.GetString("EncounterUniqueCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS MSVisit.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode Code.
        /// </summary>
        public static string EpisodeCode {
            get {
                return ResourceManager.GetString("EpisodeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode. No.
        /// </summary>
        public static string EpisodeNo {
            get {
                return ResourceManager.GetString("EpisodeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode Number.
        /// </summary>
        public static string EpisodeNumber {
            get {
                return ResourceManager.GetString("EpisodeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing.
        /// </summary>
        public static string Existing {
            get {
                return ResourceManager.GetString("Existing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Medication.
        /// </summary>
        public static string ExternalMedication {
            get {
                return ResourceManager.GetString("ExternalMedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Provider.
        /// </summary>
        public static string ExternalProvider {
            get {
                return ResourceManager.GetString("ExternalProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Provider Code.
        /// </summary>
        public static string ExternalProviderCode {
            get {
                return ResourceManager.GetString("ExternalProviderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Provider Name.
        /// </summary>
        public static string ExternalProviderName {
            get {
                return ResourceManager.GetString("ExternalProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility.
        /// </summary>
        public static string Facility {
            get {
                return ResourceManager.GetString("Facility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fall Risk Flag.
        /// </summary>
        public static string FallRiskFlag {
            get {
                return ResourceManager.GetString("FallRiskFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final ICD Completed.
        /// </summary>
        public static string FinalICDCompleted {
            get {
                return ResourceManager.GetString("FinalICDCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Up.
        /// </summary>
        public static string FollowUp {
            get {
                return ResourceManager.GetString("FollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FreeVisit.
        /// </summary>
        public static string FreeVisit {
            get {
                return ResourceManager.GetString("FreeVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gen Count.
        /// </summary>
        public static string GenCount {
            get {
                return ResourceManager.GetString("GenCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Visit.
        /// </summary>
        public static string GeneralVisit {
            get {
                return ResourceManager.GetString("GeneralVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate A04 Message.
        /// </summary>
        public static string GenerateA04Message {
            get {
                return ResourceManager.GetString("GenerateA04Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate A08 Message.
        /// </summary>
        public static string GenerateA08Message {
            get {
                return ResourceManager.GetString("GenerateA08Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate A11 Message.
        /// </summary>
        public static string GenerateA11Message {
            get {
                return ResourceManager.GetString("GenerateA11Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Lab/Package Order.
        /// </summary>
        public static string GenerateLabPackageOrder {
            get {
                return ResourceManager.GetString("GenerateLabPackageOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate OP Bill.
        /// </summary>
        public static string GenerateOPBill {
            get {
                return ResourceManager.GetString("GenerateOPBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the Server Date.
        /// </summary>
        public static string GetTheServerDate {
            get {
                return ResourceManager.GetString("GetTheServerDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HL7 Message.
        /// </summary>
        public static string HL7Message {
            get {
                return ResourceManager.GetString("HL7Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital Name.
        /// </summary>
        public static string HospitalName {
            get {
                return ResourceManager.GetString("HospitalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immunization.
        /// </summary>
        public static string Immunization {
            get {
                return ResourceManager.GetString("Immunization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Assessment Flag.
        /// </summary>
        public static string InitialAssessmentFlag {
            get {
                return ResourceManager.GetString("InitialAssessmentFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Visit.
        /// </summary>
        public static string InitialVisit {
            get {
                return ResourceManager.GetString("InitialVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injury Code.
        /// </summary>
        public static string InjuryCode {
            get {
                return ResourceManager.GetString("InjuryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injury is Open.
        /// </summary>
        public static string InjuryIsOpen {
            get {
                return ResourceManager.GetString("InjuryIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Injury Validation Required.
        /// </summary>
        public static string InjuryValidationRequired {
            get {
                return ResourceManager.GetString("InjuryValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ins. Application Number.
        /// </summary>
        public static string InsApplicationNumber {
            get {
                return ResourceManager.GetString("InsApplicationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Visit.
        /// </summary>
        public static string InsertVisit {
            get {
                return ResourceManager.GetString("InsertVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Company.
        /// </summary>
        public static string InsuranceCompany {
            get {
                return ResourceManager.GetString("InsuranceCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Company Code.
        /// </summary>
        public static string InsuranceCompanyCode {
            get {
                return ResourceManager.GetString("InsuranceCompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Name.
        /// </summary>
        public static string InsuranceName {
            get {
                return ResourceManager.GetString("InsuranceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate Visit.
        /// </summary>
        public static string IntermediateVisit {
            get {
                return ResourceManager.GetString("IntermediateVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Process Call.
        /// </summary>
        public static string InvalidProcessCall {
            get {
                return ResourceManager.GetString("InvalidProcessCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP EM Code.
        /// </summary>
        public static string IPEMCode {
            get {
                return ResourceManager.GetString("IPEMCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Chronic?.
        /// </summary>
        public static string IsChronic {
            get {
                return ResourceManager.GetString("IsChronic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Consent?.
        /// </summary>
        public static string IsConsent {
            get {
                return ResourceManager.GetString("IsConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Consultation?.
        /// </summary>
        public static string IsConsultation {
            get {
                return ResourceManager.GetString("IsConsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Deductible Collected?.
        /// </summary>
        public static string IsDeductibleCollected {
            get {
                return ResourceManager.GetString("IsDeductibleCollected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Disclosure?.
        /// </summary>
        public static string IsDisclosure {
            get {
                return ResourceManager.GetString("IsDisclosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Emergency?.
        /// </summary>
        public static string IsEmergency {
            get {
                return ResourceManager.GetString("IsEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Extend Episode?.
        /// </summary>
        public static string IsExtendEpisode {
            get {
                return ResourceManager.GetString("IsExtendEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Fall Risk?.
        /// </summary>
        public static string IsFallRisk {
            get {
                return ResourceManager.GetString("IsFallRisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Free Visit?.
        /// </summary>
        public static string IsFreeVisit {
            get {
                return ResourceManager.GetString("IsFreeVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Intimated?.
        /// </summary>
        public static string IsIntimated {
            get {
                return ResourceManager.GetString("IsIntimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is MLC?.
        /// </summary>
        public static string IsMLC {
            get {
                return ResourceManager.GetString("IsMLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Ordered?.
        /// </summary>
        public static string IsOrdered {
            get {
                return ResourceManager.GetString("IsOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Package Patient?.
        /// </summary>
        public static string IsPackagePatient {
            get {
                return ResourceManager.GetString("IsPackagePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Pre-Ordered?.
        /// </summary>
        public static string IsPreOrdered {
            get {
                return ResourceManager.GetString("IsPreOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Previous Initial Visit?.
        /// </summary>
        public static string IsPreviousInitialVisit {
            get {
                return ResourceManager.GetString("IsPreviousInitialVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Referring?.
        /// </summary>
        public static string IsReferring {
            get {
                return ResourceManager.GetString("IsReferring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is RIAYATI Consent?.
        /// </summary>
        public static string IsRIAYATIConsent {
            get {
                return ResourceManager.GetString("IsRIAYATIConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Secondary Plan?.
        /// </summary>
        public static string IsSecondaryPlan {
            get {
                return ResourceManager.GetString("IsSecondaryPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Video Consultation?.
        /// </summary>
        public static string IsVideoConsultation {
            get {
                return ResourceManager.GetString("IsVideoConsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab Automation.
        /// </summary>
        public static string LabAutomation {
            get {
                return ResourceManager.GetString("LabAutomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Balance.
        /// </summary>
        public static string LimitBalance {
            get {
                return ResourceManager.GetString("LimitBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Utilized.
        /// </summary>
        public static string LimitUtilized {
            get {
                return ResourceManager.GetString("LimitUtilized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Insurance details to Policy header.
        /// </summary>
        public static string LoadInsuranceDetailsToPolicyHeader {
            get {
                return ResourceManager.GetString("LoadInsuranceDetailsToPolicyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Nursing Flex Details.
        /// </summary>
        public static string LoadNursingFlexDetails {
            get {
                return ResourceManager.GetString("LoadNursingFlexDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maternity.
        /// </summary>
        public static string Maternity {
            get {
                return ResourceManager.GetString("Maternity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maternity Patient.
        /// </summary>
        public static string MaternityPatient {
            get {
                return ResourceManager.GetString("MaternityPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Center Flag.
        /// </summary>
        public static string MessageCenterFlag {
            get {
                return ResourceManager.GetString("MessageCenterFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MLC Code.
        /// </summary>
        public static string MLCCode {
            get {
                return ResourceManager.GetString("MLCCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MLC Description.
        /// </summary>
        public static string MLCDescription {
            get {
                return ResourceManager.GetString("MLCDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile App.
        /// </summary>
        public static string MobileApp {
            get {
                return ResourceManager.GetString("MobileApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Check In.
        /// </summary>
        public static string MobileCheckIn {
            get {
                return ResourceManager.GetString("MobileCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        public static string ModifiedDate {
            get {
                return ResourceManager.GetString("ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Primary Policy No.
        /// </summary>
        public static string ModifiedPrimaryPolicyNo {
            get {
                return ResourceManager.GetString("ModifiedPrimaryPolicyNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Sec. Policy No..
        /// </summary>
        public static string ModifiedSecPolicyNumber {
            get {
                return ResourceManager.GetString("ModifiedSecPolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Visit Package.
        /// </summary>
        public static string MultiVisitPackage {
            get {
                return ResourceManager.GetString("MultiVisitPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Visit Package Order Code.
        /// </summary>
        public static string MultiVisitPackageOrderCode {
            get {
                return ResourceManager.GetString("MultiVisitPackageOrderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Visit Package Type.
        /// </summary>
        public static string MultiVisitPackageType {
            get {
                return ResourceManager.GetString("MultiVisitPackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Visit.
        /// </summary>
        public static string NewVisit {
            get {
                return ResourceManager.GetString("NewVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Consultation.
        /// </summary>
        public static string NonConsultation {
            get {
                return ResourceManager.GetString("NonConsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Referral.
        /// </summary>
        public static string NonReferral {
            get {
                return ResourceManager.GetString("NonReferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Done.
        /// </summary>
        public static string NotDone {
            get {
                return ResourceManager.GetString("NotDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Selected.
        /// </summary>
        public static string NotSelected {
            get {
                return ResourceManager.GetString("NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.Of Bills.
        /// </summary>
        public static string NumberOfBills {
            get {
                return ResourceManager.GetString("NumberOfBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nursing Assessment Status.
        /// </summary>
        public static string NursingAssessmentStatus {
            get {
                return ResourceManager.GetString("NursingAssessmentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPD.
        /// </summary>
        public static string OPD {
            get {
                return ResourceManager.GetString("OPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ophthalmology.
        /// </summary>
        public static string Ophthalmology {
            get {
                return ResourceManager.GetString("Ophthalmology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OP Limit Balance.
        /// </summary>
        public static string OPLimitBalance {
            get {
                return ResourceManager.GetString("OPLimitBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OP Limit Utilized.
        /// </summary>
        public static string OPLimitUtilized {
            get {
                return ResourceManager.GetString("OPLimitUtilized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders Flag.
        /// </summary>
        public static string OrdersFlag {
            get {
                return ResourceManager.GetString("OrdersFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Referrals.
        /// </summary>
        public static string OtherReferrals {
            get {
                return ResourceManager.GetString("OtherReferrals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other&apos;s.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Code.
        /// </summary>
        public static string PackageCode {
            get {
                return ResourceManager.GetString("PackageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Description.
        /// </summary>
        public static string PackageDescription {
            get {
                return ResourceManager.GetString("PackageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Type.
        /// </summary>
        public static string PackageType {
            get {
                return ResourceManager.GetString("PackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Follow Up.
        /// </summary>
        public static string PaidFollowUp {
            get {
                return ResourceManager.GetString("PaidFollowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Code.
        /// </summary>
        public static string PatientCode {
            get {
                return ResourceManager.GetString("PatientCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Complain Flag.
        /// </summary>
        public static string PatientComplainFlag {
            get {
                return ResourceManager.GetString("PatientComplainFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Employer Code.
        /// </summary>
        public static string PatientEmployerCode {
            get {
                return ResourceManager.GetString("PatientEmployerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Name.
        /// </summary>
        public static string PatientName {
            get {
                return ResourceManager.GetString("PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Type.
        /// </summary>
        public static string PatientType {
            get {
                return ResourceManager.GetString("PatientType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pharmacy Visit.
        /// </summary>
        public static string PharmacyVisit {
            get {
                return ResourceManager.GetString("PharmacyVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Code.
        /// </summary>
        public static string PlanCode {
            get {
                return ResourceManager.GetString("PlanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Name.
        /// </summary>
        public static string PlanName {
            get {
                return ResourceManager.GetString("PlanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Police Station Name.
        /// </summary>
        public static string PoliceStationName {
            get {
                return ResourceManager.GetString("PoliceStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Expiry Date.
        /// </summary>
        public static string PolicyExpiryDate {
            get {
                return ResourceManager.GetString("PolicyExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Group Code.
        /// </summary>
        public static string PolicyGroupCode {
            get {
                return ResourceManager.GetString("PolicyGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Group Description.
        /// </summary>
        public static string PolicyGroupDescription {
            get {
                return ResourceManager.GetString("PolicyGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Number.
        /// </summary>
        public static string PolicyNumber {
            get {
                return ResourceManager.GetString("PolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Start Date.
        /// </summary>
        public static string PolicyStartDate {
            get {
                return ResourceManager.GetString("PolicyStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Surgical.
        /// </summary>
        public static string PostSurgical {
            get {
                return ResourceManager.GetString("PostSurgical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Authorization Required.
        /// </summary>
        public static string PreAuthorizationRequired {
            get {
                return ResourceManager.GetString("PreAuthorizationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription Type.
        /// </summary>
        public static string PrescriptionType {
            get {
                return ResourceManager.GetString("PrescriptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Visit Date.
        /// </summary>
        public static string PreviousVisitDate {
            get {
                return ResourceManager.GetString("PreviousVisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Visit Provider Code.
        /// </summary>
        public static string PreviousVisitProviderCode {
            get {
                return ResourceManager.GetString("PreviousVisitProviderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure.
        /// </summary>
        public static string Procedure {
            get {
                return ResourceManager.GetString("Procedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Code.
        /// </summary>
        public static string ProviderCode {
            get {
                return ResourceManager.GetString("ProviderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Name.
        /// </summary>
        public static string ProviderName {
            get {
                return ResourceManager.GetString("ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider wise.
        /// </summary>
        public static string ProviderWise {
            get {
                return ResourceManager.GetString("ProviderWise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provisional ICD Completed.
        /// </summary>
        public static string ProvisionalICDCompleted {
            get {
                return ResourceManager.GetString("ProvisionalICDCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue Number.
        /// </summary>
        public static string QueueNumber {
            get {
                return ResourceManager.GetString("QueueNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue No..
        /// </summary>
        public static string QueueNumber2 {
            get {
                return ResourceManager.GetString("QueueNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Calculate PreAuthorization.
        /// </summary>
        public static string ReCalculatePreauthorization {
            get {
                return ResourceManager.GetString("ReCalculatePreauthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Code.
        /// </summary>
        public static string ReferenceCode {
            get {
                return ResourceManager.GetString("ReferenceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Detail.
        /// </summary>
        public static string ReferenceDetail {
            get {
                return ResourceManager.GetString("ReferenceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Type.
        /// </summary>
        public static string ReferenceType {
            get {
                return ResourceManager.GetString("ReferenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral Employee Code.
        /// </summary>
        public static string ReferralEmployeeCode {
            get {
                return ResourceManager.GetString("ReferralEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral Name.
        /// </summary>
        public static string ReferralName {
            get {
                return ResourceManager.GetString("ReferralName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral Provider Code.
        /// </summary>
        public static string ReferralProviderCode {
            get {
                return ResourceManager.GetString("ReferralProviderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral Visit.
        /// </summary>
        public static string ReferralVisit {
            get {
                return ResourceManager.GetString("ReferralVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral Visit Check.
        /// </summary>
        public static string ReferralVisitCheck {
            get {
                return ResourceManager.GetString("ReferralVisitCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referred Name.
        /// </summary>
        public static string ReferredName {
            get {
                return ResourceManager.GetString("ReferredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Bills.
        /// </summary>
        public static string RegisterBills {
            get {
                return ResourceManager.GetString("RegisterBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requisition No.
        /// </summary>
        public static string RequisitionNo {
            get {
                return ResourceManager.GetString("RequisitionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results Flag.
        /// </summary>
        public static string ResultsFlag {
            get {
                return ResourceManager.GetString("ResultsFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re Visit.
        /// </summary>
        public static string ReVisit {
            get {
                return ResourceManager.GetString("ReVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Customer Code.
        /// </summary>
        public static string SecondaryCustomerCode {
            get {
                return ResourceManager.GetString("SecondaryCustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Customer Type.
        /// </summary>
        public static string SecondaryCustomerType {
            get {
                return ResourceManager.GetString("SecondaryCustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Plan Code.
        /// </summary>
        public static string SecondaryPlanCode {
            get {
                return ResourceManager.GetString("SecondaryPlanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Policy Expiry Date.
        /// </summary>
        public static string SecondaryPolicyExpiryDate {
            get {
                return ResourceManager.GetString("SecondaryPolicyExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Policy Group Code.
        /// </summary>
        public static string SecondaryPolicyGroupCode {
            get {
                return ResourceManager.GetString("SecondaryPolicyGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Policy No..
        /// </summary>
        public static string SecondaryPolicyNumber {
            get {
                return ResourceManager.GetString("SecondaryPolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Policy Start Date.
        /// </summary>
        public static string SecondaryPolicyStartDate {
            get {
                return ResourceManager.GetString("SecondaryPolicyStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Sponsor Code.
        /// </summary>
        public static string SecondarySponsorCode {
            get {
                return ResourceManager.GetString("SecondarySponsorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self.
        /// </summary>
        public static string Self {
            get {
                return ResourceManager.GetString("Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Provider.
        /// </summary>
        public static string SendToProvider {
            get {
                return ResourceManager.GetString("SendToProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOAP No..
        /// </summary>
        public static string SOAPNumber {
            get {
                return ResourceManager.GetString("SOAPNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Count.
        /// </summary>
        public static string SpecialCount {
            get {
                return ResourceManager.GetString("SpecialCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality Code.
        /// </summary>
        public static string SpecialityCode {
            get {
                return ResourceManager.GetString("SpecialityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality Department.
        /// </summary>
        public static string SpecialityDepartment {
            get {
                return ResourceManager.GetString("SpecialityDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality Description.
        /// </summary>
        public static string SpecialityDescription {
            get {
                return ResourceManager.GetString("SpecialityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor Code.
        /// </summary>
        public static string SponsorCode {
            get {
                return ResourceManager.GetString("SponsorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsored By.
        /// </summary>
        public static string SponsoredBy {
            get {
                return ResourceManager.GetString("SponsoredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Package.
        /// </summary>
        public static string StaticPackage {
            get {
                return ResourceManager.GetString("StaticPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer By.
        /// </summary>
        public static string TransferBy {
            get {
                return ResourceManager.GetString("TransferBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Date.
        /// </summary>
        public static string TransferDate {
            get {
                return ResourceManager.GetString("TransferDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Reason.
        /// </summary>
        public static string TransferReason {
            get {
                return ResourceManager.GetString("TransferReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred Admission Code.
        /// </summary>
        public static string TransferredAdmissionCode {
            get {
                return ResourceManager.GetString("TransferredAdmissionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Time.
        /// </summary>
        public static string TransferTime {
            get {
                return ResourceManager.GetString("TransferTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Of Visit.
        /// </summary>
        public static string TypeOfVisit {
            get {
                return ResourceManager.GetString("TypeOfVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Code.
        /// </summary>
        public static string UnitCode {
            get {
                return ResourceManager.GetString("UnitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Description.
        /// </summary>
        public static string UnitDescription {
            get {
                return ResourceManager.GetString("UnitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Lab Print Status.
        /// </summary>
        public static string UpdateLabPrintStatus {
            get {
                return ResourceManager.GetString("UpdateLabPrintStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Provider.
        /// </summary>
        public static string UpdateProvider {
            get {
                return ResourceManager.GetString("UpdateProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Video Consultation.
        /// </summary>
        public static string UpdateVideoConsultation {
            get {
                return ResourceManager.GetString("UpdateVideoConsultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Visit.
        /// </summary>
        public static string UpdateVisit {
            get {
                return ResourceManager.GetString("UpdateVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Visit Close in EHR.
        /// </summary>
        public static string UpdateVisitCloseInEHR {
            get {
                return ResourceManager.GetString("UpdateVisitCloseInEHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Visit in Triage.
        /// </summary>
        public static string UpdateVisitInTriage {
            get {
                return ResourceManager.GetString("UpdateVisitInTriage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Save Process.
        /// </summary>
        public static string ValidateSaveProcess {
            get {
                return ResourceManager.GetString("ValidateSaveProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit.
        /// </summary>
        public static string Visit {
            get {
                return ResourceManager.GetString("Visit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Closed.
        /// </summary>
        public static string VisitClosed {
            get {
                return ResourceManager.GetString("VisitClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Code.
        /// </summary>
        public static string VisitCode {
            get {
                return ResourceManager.GetString("VisitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Date.
        /// </summary>
        public static string VisitDate {
            get {
                return ResourceManager.GetString("VisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Department Number.
        /// </summary>
        public static string VisitDepartmentNumber {
            get {
                return ResourceManager.GetString("VisitDepartmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VisitExistEnd.
        /// </summary>
        public static string VisitExistEnd {
            get {
                return ResourceManager.GetString("VisitExistEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Exist End Time.
        /// </summary>
        public static string VisitExistEndTime {
            get {
                return ResourceManager.GetString("VisitExistEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Expiry Date.
        /// </summary>
        public static string VisitExpiryDate {
            get {
                return ResourceManager.GetString("VisitExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit From Appointment.
        /// </summary>
        public static string VisitFromAppointment {
            get {
                return ResourceManager.GetString("VisitFromAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit level Copay.
        /// </summary>
        public static string VisitLevelCopay {
            get {
                return ResourceManager.GetString("VisitLevelCopay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Modified.
        /// </summary>
        public static string VisitModified {
            get {
                return ResourceManager.GetString("VisitModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Purpose.
        /// </summary>
        public static string VisitPurpose {
            get {
                return ResourceManager.GetString("VisitPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Time.
        /// </summary>
        public static string VisitTime {
            get {
                return ResourceManager.GetString("VisitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Type.
        /// </summary>
        public static string VisitType {
            get {
                return ResourceManager.GetString("VisitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wound Certified Date.
        /// </summary>
        public static string WoundCertifiedDate {
            get {
                return ResourceManager.GetString("WoundCertifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
