//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mimsys.MS.Resources.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PatientPolicyResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PatientPolicyResx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mimsys.MS.Resources.Forms.PatientPolicyResx", typeof(PatientPolicyResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Deductible.
        /// </summary>
        public static string AnnualDeductible {
            get {
                return ResourceManager.GetString("AnnualDeductible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Salary.
        /// </summary>
        public static string BasicSalary {
            get {
                return ResourceManager.GetString("BasicSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-Payment Amount.
        /// </summary>
        public static string CoPaymentAmount {
            get {
                return ResourceManager.GetString("CoPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Clients.
        /// </summary>
        public static string CorporateClients {
            get {
                return ResourceManager.GetString("CorporateClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criedt Patient.
        /// </summary>
        public static string CriedtPatient {
            get {
                return ResourceManager.GetString("CriedtPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Primary Insurance.
        /// </summary>
        public static string CurrentPrimaryInsurance {
            get {
                return ResourceManager.GetString("CurrentPrimaryInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type.
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductible Balance.
        /// </summary>
        public static string DeductibleBalance {
            get {
                return ResourceManager.GetString("DeductibleBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent.
        /// </summary>
        public static string Dependent {
            get {
                return ResourceManager.GetString("Dependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent No..
        /// </summary>
        public static string DependentNumber {
            get {
                return ResourceManager.GetString("DependentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eligible.
        /// </summary>
        public static string Eligible {
            get {
                return ResourceManager.GetString("Eligible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        public static string EmployeeID {
            get {
                return ResourceManager.GetString("EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee MRN Number.
        /// </summary>
        public static string EmployeeMRNNumber {
            get {
                return ResourceManager.GetString("EmployeeMRNNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer.
        /// </summary>
        public static string Employer {
            get {
                return ResourceManager.GetString("Employer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Name.
        /// </summary>
        public static string EmployerName {
            get {
                return ResourceManager.GetString("EmployerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS PatientPolicy.
        /// </summary>
        public static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fund Brand ID.
        /// </summary>
        public static string FundBrandID {
            get {
                return ResourceManager.GetString("FundBrandID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ins. Application Number.
        /// </summary>
        public static string InsApplicationNumber {
            get {
                return ResourceManager.GetString("InsApplicationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ins. Application Required.
        /// </summary>
        public static string InsApplicationRequired {
            get {
                return ResourceManager.GetString("InsApplicationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Company.
        /// </summary>
        public static string InsuranceCompany {
            get {
                return ResourceManager.GetString("InsuranceCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance ID Path.
        /// </summary>
        public static string InsuranceIDPath {
            get {
                return ResourceManager.GetString("InsuranceIDPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Referral.
        /// </summary>
        public static string InsuranceReferral {
            get {
                return ResourceManager.GetString("InsuranceReferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Process Call.
        /// </summary>
        public static string InvalidProcessCall {
            get {
                return ResourceManager.GetString("InvalidProcessCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Aid  Company.
        /// </summary>
        public static string MedicalAidCompany {
            get {
                return ResourceManager.GetString("MedicalAidCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        public static string ModifiedDate {
            get {
                return ResourceManager.GetString("ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Y/N.
        /// </summary>
        public static string NetworkYN {
            get {
                return ResourceManager.GetString("NetworkYN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Eligible.
        /// </summary>
        public static string NotEligible {
            get {
                return ResourceManager.GetString("NotEligible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Selected.
        /// </summary>
        public static string NotSelected {
            get {
                return ResourceManager.GetString("NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Expiry Date.
        /// </summary>
        public static string OldExpiryDate {
            get {
                return ResourceManager.GetString("OldExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Code.
        /// </summary>
        public static string PatientCode {
            get {
                return ResourceManager.GetString("PatientCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Code.
        /// </summary>
        public static string PlanCode {
            get {
                return ResourceManager.GetString("PlanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Type.
        /// </summary>
        public static string PlanType {
            get {
                return ResourceManager.GetString("PlanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Description.
        /// </summary>
        public static string PolicyDescription {
            get {
                return ResourceManager.GetString("PolicyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Name.
        /// </summary>
        public static string PolicyName {
            get {
                return ResourceManager.GetString("PolicyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy No..
        /// </summary>
        public static string PolicyNumber {
            get {
                return ResourceManager.GetString("PolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Insurance Card No..
        /// </summary>
        public static string PrimaryInsuranceCardNumber {
            get {
                return ResourceManager.GetString("PrimaryInsuranceCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        public static string Principal {
            get {
                return ResourceManager.GetString("Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal Employee No..
        /// </summary>
        public static string PrincipalEmployeeNumber {
            get {
                return ResourceManager.GetString("PrincipalEmployeeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principle Type.
        /// </summary>
        public static string PrincipleType {
            get {
                return ResourceManager.GetString("PrincipleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PRPOLEXPDT {
            get {
                return ResourceManager.GetString("PRPOLEXPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec. Customer Type.
        /// </summary>
        public static string SecCustomerType {
            get {
                return ResourceManager.GetString("SecCustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec. Expiry Date.
        /// </summary>
        public static string SecExpiryDate {
            get {
                return ResourceManager.GetString("SecExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec. Insurance Company.
        /// </summary>
        public static string SecInsuranceCompany {
            get {
                return ResourceManager.GetString("SecInsuranceCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec. Insurance Policy.
        /// </summary>
        public static string SecInsurancePolicy {
            get {
                return ResourceManager.GetString("SecInsurancePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Plan Applicable.
        /// </summary>
        public static string SecondaryPlanApplicable {
            get {
                return ResourceManager.GetString("SecondaryPlanApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Sponsor Code.
        /// </summary>
        public static string SecondarySponsorCode {
            get {
                return ResourceManager.GetString("SecondarySponsorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Sponsored By.
        /// </summary>
        public static string SecondarySponsoredBy {
            get {
                return ResourceManager.GetString("SecondarySponsoredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Sponsor Name.
        /// </summary>
        public static string SecondarySponsorName {
            get {
                return ResourceManager.GetString("SecondarySponsorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec. Plan Card No..
        /// </summary>
        public static string SecPlanCardNumber {
            get {
                return ResourceManager.GetString("SecPlanCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec. Plan Dependent No..
        /// </summary>
        public static string SecPlanDependentNumber {
            get {
                return ResourceManager.GetString("SecPlanDependentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec. Policy Group Code.
        /// </summary>
        public static string SecPolicyGroupCode {
            get {
                return ResourceManager.GetString("SecPolicyGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec. Policy Number.
        /// </summary>
        public static string SecPolicyNumber {
            get {
                return ResourceManager.GetString("SecPolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sec. Start Date.
        /// </summary>
        public static string SecStartDate {
            get {
                return ResourceManager.GetString("SecStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self.
        /// </summary>
        public static string Self {
            get {
                return ResourceManager.GetString("Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SEPOLEXPDT {
            get {
                return ResourceManager.GetString("SEPOLEXPDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor Code.
        /// </summary>
        public static string SponsorCode {
            get {
                return ResourceManager.GetString("SponsorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsored By.
        /// </summary>
        public static string SponsoredBy {
            get {
                return ResourceManager.GetString("SponsoredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPA.
        /// </summary>
        public static string TPA {
            get {
                return ResourceManager.GetString("TPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal Patient Identifier(UPI.
        /// </summary>
        public static string UniversalPatientIdentifierUPI {
            get {
                return ResourceManager.GetString("UniversalPatientIdentifierUPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Malafi.
        /// </summary>
        public static string UpdateMalafi {
            get {
                return ResourceManager.GetString("UpdateMalafi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Consultation Eligiblity.
        /// </summary>
        public static string VideoConsultationEligiblity {
            get {
                return ResourceManager.GetString("VideoConsultationEligiblity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string VISITID {
            get {
                return ResourceManager.GetString("VISITID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
